/**
 * イベントデモ用ダミー受注データ（50件）
 * 各タスクフィルタが正しく動作するよう設計
 *
 * TaskProcessors の判定条件（ecforce-api.js）に合わせたフィールド設定:
 *  - paymentError : payment_state が PAYMENT_ERROR_STATES に含まれる
 *  - nameAnomaly  : is_first_order=true + judgePersonName で異常検出
 *  - npPayment    : payment_method_id in [57, 24, 61]
 *  - singleItem   : line_items に product_code 'EA00'/'WB00'/'SU00' を含む
 *  - purchaseUrl  : times===1 + purchase_url に 'defo'/'test' を含む
 *  - oplux        : times===1 + o_plux_result==='REVIEW'
 *  - duplicate    : 同一氏名または同一住所ペア
 *  - addressCorrection: is_first_order=true（全件がタスク対象）
 */

// ─────────────────────────────────────────────────────────────────────────────
// グループ1: 決済エラー（6件） id: 200001-200006
// ─────────────────────────────────────────────────────────────────────────────
const paymentErrorOrders = [
  {
    id: 200001,
    number: 'EC-0200001',
    state: 'complete',
    payment_state: 'sales_failed',
    shipment_state: 'ready',
    times: 3,
    is_first_order: false,
    payment_method_id: 1,
    payment_method_name: 'クレジットカード',
    o_plux_result: null,
    o_plux_description: null,
    purchase_url: 'https://lifewell.jp/p/3001',
    completed_at: '2026-04-30T08:15:00+09:00',
    subs_order_id: 50001,
    shipping_address: {
      family_name: '山田',
      given_name: '健一',
      zip: '160-0022',
      prefecture: '東京都',
      city: '新宿区',
      street: '新宿3-3-12',
      building: 'ラグナ新宿 405号',
    },
    line_items: [
      { product_code: 'LW-1001', name: 'Lifewellコラーゲン 60粒', quantity: 1, price: 5400 },
    ],
  },
  {
    id: 200002,
    number: 'EC-0200002',
    state: 'complete',
    payment_state: 'failed',
    shipment_state: 'ready',
    times: 2,
    is_first_order: false,
    payment_method_id: 1,
    payment_method_name: 'クレジットカード',
    o_plux_result: null,
    o_plux_description: null,
    purchase_url: 'https://lifewell.jp/p/3002',
    completed_at: '2026-04-30T09:20:00+09:00',
    subs_order_id: null,
    shipping_address: {
      family_name: '中村',
      given_name: '美穂',
      zip: '231-0015',
      prefecture: '神奈川県',
      city: '横浜市中区',
      street: '尾上町4-47',
      building: '',
    },
    line_items: [
      { product_code: 'LW-1002', name: 'Lifewellビタミンサプリ 30粒', quantity: 2, price: 3800 },
    ],
  },
  {
    id: 200003,
    number: 'EC-0200003',
    state: 'complete',
    payment_state: 'auth_failed',
    shipment_state: 'ready',
    times: 4,
    is_first_order: false,
    payment_method_id: 1,
    payment_method_name: 'クレジットカード',
    o_plux_result: null,
    o_plux_description: null,
    purchase_url: 'https://lifewell.jp/p/3003',
    completed_at: '2026-04-30T10:05:00+09:00',
    subs_order_id: 50003,
    shipping_address: {
      family_name: '佐々木',
      given_name: '拓也',
      zip: '530-0001',
      prefecture: '大阪府',
      city: '大阪市北区',
      street: '梅田1-2-2',
      building: 'オービックビル 1201号',
    },
    line_items: [
      { product_code: 'LW-1003', name: 'Lifewell乳酸菌プラス 90粒', quantity: 1, price: 6800 },
    ],
  },
  {
    id: 200004,
    number: 'EC-0200004',
    state: 'complete',
    payment_state: 'sales_failed',
    shipment_state: 'pending',
    times: 6,
    is_first_order: false,
    payment_method_id: 1,
    payment_method_name: 'クレジットカード',
    o_plux_result: null,
    o_plux_description: null,
    purchase_url: 'https://lifewell.jp/p/3004',
    completed_at: '2026-04-30T11:00:00+09:00',
    subs_order_id: 50004,
    shipping_address: {
      family_name: '小林',
      given_name: '恵子',
      zip: '460-0008',
      prefecture: '愛知県',
      city: '名古屋市中区',
      street: '栄3-14-13',
      building: '',
    },
    line_items: [
      { product_code: 'LW-1001', name: 'Lifewellコラーゲン 60粒', quantity: 3, price: 5400 },
    ],
  },
  {
    id: 200005,
    number: 'EC-0200005',
    state: 'complete',
    payment_state: 'void_failed',
    shipment_state: 'ready',
    times: 2,
    is_first_order: false,
    payment_method_id: 1,
    payment_method_name: 'クレジットカード',
    o_plux_result: null,
    o_plux_description: null,
    purchase_url: 'https://lifewell.jp/p/3005',
    completed_at: '2026-04-30T12:30:00+09:00',
    subs_order_id: null,
    shipping_address: {
      family_name: '松田',
      given_name: '浩二',
      zip: '812-0011',
      prefecture: '福岡県',
      city: '福岡市博多区',
      street: '博多駅前2-1-1',
      building: 'フコク生命ビル 803号',
    },
    line_items: [
      { product_code: 'LW-1004', name: 'Lifewellマルチビタミン 60粒', quantity: 1, price: 4200 },
    ],
  },
  {
    id: 200006,
    number: 'EC-0200006',
    state: 'complete',
    payment_state: 'update_failed',
    shipment_state: 'ready',
    times: 5,
    is_first_order: false,
    payment_method_id: 1,
    payment_method_name: 'クレジットカード',
    o_plux_result: null,
    o_plux_description: null,
    purchase_url: 'https://lifewell.jp/p/3006',
    completed_at: '2026-04-30T13:45:00+09:00',
    subs_order_id: 50006,
    shipping_address: {
      family_name: '高橋',
      given_name: '典子',
      zip: '060-0001',
      prefecture: '北海道',
      city: '札幌市中央区',
      street: '北1条西2丁目',
      building: '',
    },
    line_items: [
      { product_code: 'LW-1002', name: 'Lifewellビタミンサプリ 30粒', quantity: 2, price: 3800 },
    ],
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// グループ2: 氏名不備（7件） id: 200007-200013
// is_first_order=true で judgePersonName が異常を検出する名前
// ─────────────────────────────────────────────────────────────────────────────
const nameAnomalyOrders = [
  {
    // テスト文字列を含む名前
    id: 200007,
    number: 'EC-0200007',
    state: 'complete',
    payment_state: 'paid',
    shipment_state: 'ready',
    times: 1,
    is_first_order: true,
    payment_method_id: 1,
    payment_method_name: 'クレジットカード',
    o_plux_result: 'OK',
    o_plux_description: null,
    purchase_url: 'https://lifewell.jp/p/3007',
    completed_at: '2026-04-30T08:00:00+09:00',
    subs_order_id: null,
    shipping_address: {
      family_name: 'テスト',
      given_name: '太郎',
      zip: '150-0001',
      prefecture: '東京都',
      city: '渋谷区',
      street: '神宮前1-1-1',
      building: '',
    },
    line_items: [
      { product_code: 'LW-1001', name: 'Lifewellコラーゲン 60粒', quantity: 1, price: 5400 },
    ],
  },
  {
    // ひらがなのみ5文字以上（姓）
    id: 200008,
    number: 'EC-0200008',
    state: 'complete',
    payment_state: 'paid',
    shipment_state: 'ready',
    times: 1,
    is_first_order: true,
    payment_method_id: 1,
    payment_method_name: 'クレジットカード',
    o_plux_result: 'OK',
    o_plux_description: null,
    purchase_url: 'https://lifewell.jp/p/3008',
    completed_at: '2026-04-30T08:30:00+09:00',
    subs_order_id: null,
    shipping_address: {
      family_name: 'よしかわ',
      given_name: 'さとみ',
      zip: '220-0012',
      prefecture: '神奈川県',
      city: '横浜市西区',
      street: 'みなとみらい3-5-1',
      building: 'クイーンズスクエア A棟 2506号',
    },
    line_items: [
      { product_code: 'LW-1003', name: 'Lifewell乳酸菌プラス 90粒', quantity: 1, price: 6800 },
    ],
  },
  {
    // 漢字+ひらがな混在（姓の末尾がひらがな1文字）
    id: 200009,
    number: 'EC-0200009',
    state: 'complete',
    payment_state: 'paid',
    shipment_state: 'ready',
    times: 1,
    is_first_order: true,
    payment_method_id: 1,
    payment_method_name: 'クレジットカード',
    o_plux_result: 'OK',
    o_plux_description: null,
    purchase_url: 'https://lifewell.jp/p/3009',
    completed_at: '2026-04-30T09:10:00+09:00',
    subs_order_id: null,
    shipping_address: {
      family_name: '田中ら',
      given_name: '花子',
      zip: '540-0008',
      prefecture: '大阪府',
      city: '大阪市中央区',
      street: '大手前2-1-22',
      building: '',
    },
    line_items: [
      { product_code: 'LW-1004', name: 'Lifewellマルチビタミン 60粒', quantity: 2, price: 4200 },
    ],
  },
  {
    // 数字のみの名前
    id: 200010,
    number: 'EC-0200010',
    state: 'complete',
    payment_state: 'paid',
    shipment_state: 'ready',
    times: 1,
    is_first_order: true,
    payment_method_id: 1,
    payment_method_name: 'クレジットカード',
    o_plux_result: 'OK',
    o_plux_description: null,
    purchase_url: 'https://lifewell.jp/p/3010',
    completed_at: '2026-04-30T09:45:00+09:00',
    subs_order_id: null,
    shipping_address: {
      family_name: '12345',
      given_name: '67890',
      zip: '010-0001',
      prefecture: '秋田県',
      city: '秋田市中通',
      street: '1-4-1',
      building: '',
    },
    line_items: [
      { product_code: 'LW-1001', name: 'Lifewellコラーゲン 60粒', quantity: 1, price: 5400 },
    ],
  },
  {
    // ひらがなのみ5文字以上（名）
    id: 200011,
    number: 'EC-0200011',
    state: 'complete',
    payment_state: 'paid',
    shipment_state: 'ready',
    times: 1,
    is_first_order: true,
    payment_method_id: 1,
    payment_method_name: 'クレジットカード',
    o_plux_result: 'OK',
    o_plux_description: null,
    purchase_url: 'https://lifewell.jp/p/3011',
    completed_at: '2026-04-30T10:20:00+09:00',
    subs_order_id: null,
    shipping_address: {
      family_name: '鈴木',
      given_name: 'みさきこ',
      zip: '980-0021',
      prefecture: '宮城県',
      city: '仙台市青葉区',
      street: '中央1-3-1',
      building: '',
    },
    line_items: [
      { product_code: 'LW-1002', name: 'Lifewellビタミンサプリ 30粒', quantity: 1, price: 3800 },
    ],
  },
  {
    // O-PLUX振り仮名エラー
    id: 200012,
    number: 'EC-0200012',
    state: 'complete',
    payment_state: 'paid',
    shipment_state: 'ready',
    times: 1,
    is_first_order: true,
    payment_method_id: 1,
    payment_method_name: 'クレジットカード',
    o_plux_result: 'OK',
    o_plux_description: 'フリガナ不一致のため要確認。振り仮名：ミヤケ → 三宅',
    purchase_url: 'https://lifewell.jp/p/3012',
    completed_at: '2026-04-30T11:00:00+09:00',
    subs_order_id: null,
    shipping_address: {
      family_name: '三宅',
      given_name: '奈津子',
      zip: '730-0011',
      prefecture: '広島県',
      city: '広島市中区',
      street: '基町6-27',
      building: '',
    },
    line_items: [
      { product_code: 'LW-1003', name: 'Lifewell乳酸菌プラス 90粒', quantity: 1, price: 6800 },
    ],
  },
  {
    // test文字列を含む（名）
    id: 200013,
    number: 'EC-0200013',
    state: 'complete',
    payment_state: 'paid',
    shipment_state: 'ready',
    times: 1,
    is_first_order: true,
    payment_method_id: 1,
    payment_method_name: 'クレジットカード',
    o_plux_result: 'OK',
    o_plux_description: null,
    purchase_url: 'https://lifewell.jp/p/3013',
    completed_at: '2026-04-30T11:30:00+09:00',
    subs_order_id: null,
    shipping_address: {
      family_name: 'テスト',
      given_name: 'テスト',
      zip: '651-0087',
      prefecture: '兵庫県',
      city: '神戸市中央区',
      street: '御幸通8-1-6',
      building: 'NTT西日本ビル 301号',
    },
    line_items: [
      { product_code: 'LW-1001', name: 'Lifewellコラーゲン 60粒', quantity: 1, price: 5400 },
    ],
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// グループ3: NP後払い（5件） id: 200014-200018
// payment_method_id: 57
// ─────────────────────────────────────────────────────────────────────────────
const npPaymentOrders = [
  {
    id: 200014,
    number: 'EC-0200014',
    state: 'complete',
    payment_state: 'paid',
    shipment_state: 'ready',
    times: 1,
    is_first_order: true,
    payment_method_id: 57,
    payment_method_name: 'NP後払い',
    o_plux_result: 'OK',
    o_plux_description: null,
    purchase_url: 'https://lifewell.jp/p/3014',
    completed_at: '2026-04-30T08:10:00+09:00',
    subs_order_id: 50014,
    shipping_address: {
      family_name: '伊藤',
      given_name: '啓介',
      zip: '170-0013',
      prefecture: '東京都',
      city: '豊島区',
      street: '東池袋1-21-11',
      building: '',
    },
    line_items: [
      { product_code: 'LW-1001', name: 'Lifewellコラーゲン 60粒', quantity: 1, price: 5400 },
    ],
  },
  {
    id: 200015,
    number: 'EC-0200015',
    state: 'complete',
    payment_state: 'paid',
    shipment_state: 'ready',
    times: 1,
    is_first_order: true,
    payment_method_id: 57,
    payment_method_name: 'NP後払い',
    o_plux_result: 'OK',
    o_plux_description: null,
    purchase_url: 'https://lifewell.jp/p/3015',
    completed_at: '2026-04-30T09:00:00+09:00',
    subs_order_id: null,
    shipping_address: {
      family_name: '渡辺',
      given_name: '純子',
      zip: '456-0031',
      prefecture: '愛知県',
      city: '名古屋市熱田区',
      street: '神宮3-1-1',
      building: '',
    },
    line_items: [
      { product_code: 'LW-1004', name: 'Lifewellマルチビタミン 60粒', quantity: 2, price: 4200 },
    ],
  },
  {
    id: 200016,
    number: 'EC-0200016',
    state: 'complete',
    payment_state: 'paid',
    shipment_state: 'ready',
    times: 2,
    is_first_order: false,
    payment_method_id: 57,
    payment_method_name: 'NP後払い',
    o_plux_result: null,
    o_plux_description: null,
    purchase_url: 'https://lifewell.jp/p/3016',
    completed_at: '2026-04-30T10:00:00+09:00',
    subs_order_id: 50016,
    shipping_address: {
      family_name: '加藤',
      given_name: '秀樹',
      zip: '600-8216',
      prefecture: '京都府',
      city: '京都市下京区',
      street: '烏丸通六条下る北若松町576',
      building: '',
    },
    line_items: [
      { product_code: 'LW-1002', name: 'Lifewellビタミンサプリ 30粒', quantity: 1, price: 3800 },
    ],
  },
  {
    id: 200017,
    number: 'EC-0200017',
    state: 'complete',
    payment_state: 'paid',
    shipment_state: 'ready',
    times: 1,
    is_first_order: true,
    payment_method_id: 57,
    payment_method_name: 'NP後払い',
    o_plux_result: 'OK',
    o_plux_description: null,
    purchase_url: 'https://lifewell.jp/p/3017',
    completed_at: '2026-04-30T11:20:00+09:00',
    subs_order_id: null,
    shipping_address: {
      family_name: '木村',
      given_name: '里美',
      zip: '900-0015',
      prefecture: '沖縄県',
      city: '那覇市久茂地',
      street: '3-15-1',
      building: 'パシフィックホテル 503号',
    },
    line_items: [
      { product_code: 'LW-1003', name: 'Lifewell乳酸菌プラス 90粒', quantity: 1, price: 6800 },
    ],
  },
  {
    id: 200018,
    number: 'EC-0200018',
    state: 'complete',
    payment_state: 'paid',
    shipment_state: 'ready',
    times: 3,
    is_first_order: false,
    payment_method_id: 57,
    payment_method_name: 'NP後払い',
    o_plux_result: null,
    o_plux_description: null,
    purchase_url: 'https://lifewell.jp/p/3018',
    completed_at: '2026-04-30T12:00:00+09:00',
    subs_order_id: 50018,
    shipping_address: {
      family_name: '石川',
      given_name: '雅美',
      zip: '920-0911',
      prefecture: '石川県',
      city: '金沢市橋場町',
      street: '3-1',
      building: '',
    },
    line_items: [
      { product_code: 'LW-1001', name: 'Lifewellコラーゲン 60粒', quantity: 2, price: 5400 },
    ],
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// グループ4: 単品注文（5件） id: 200019-200023
// line_items に product_code 'EA00'/'WB00'/'SU00' を含む
// ─────────────────────────────────────────────────────────────────────────────
const singleItemOrders = [
  {
    id: 200019,
    number: 'EC-0200019',
    state: 'complete',
    payment_state: 'paid',
    shipment_state: 'ready',
    times: 1,
    is_first_order: true,
    payment_method_id: 1,
    payment_method_name: 'クレジットカード',
    o_plux_result: 'OK',
    o_plux_description: null,
    purchase_url: 'https://lifewell.jp/p/3019',
    completed_at: '2026-04-30T08:05:00+09:00',
    subs_order_id: null,
    shipping_address: {
      family_name: '橋本',
      given_name: '一郎',
      zip: '102-0083',
      prefecture: '東京都',
      city: '千代田区',
      street: '麹町4-2-6',
      building: 'イトーピア麹町ビル 1201号',
    },
    line_items: [
      { product_code: 'EA00', name: 'Lifewell エイジングケア（単品）', quantity: 1, price: 5980 },
    ],
  },
  {
    id: 200020,
    number: 'EC-0200020',
    state: 'complete',
    payment_state: 'paid',
    shipment_state: 'ready',
    times: 2,
    is_first_order: false,
    payment_method_id: 1,
    payment_method_name: 'クレジットカード',
    o_plux_result: null,
    o_plux_description: null,
    purchase_url: 'https://lifewell.jp/p/3020',
    completed_at: '2026-04-30T09:30:00+09:00',
    subs_order_id: null,
    shipping_address: {
      family_name: '前田',
      given_name: '知子',
      zip: '550-0011',
      prefecture: '大阪府',
      city: '大阪市西区',
      street: '阿波座1-3-5',
      building: '',
    },
    line_items: [
      { product_code: 'WB00', name: 'Lifewell ウォーターバランス（単品）', quantity: 2, price: 4480 },
    ],
  },
  {
    id: 200021,
    number: 'EC-0200021',
    state: 'complete',
    payment_state: 'paid',
    shipment_state: 'ready',
    times: 1,
    is_first_order: true,
    payment_method_id: 1,
    payment_method_name: 'クレジットカード',
    o_plux_result: 'OK',
    o_plux_description: null,
    purchase_url: 'https://lifewell.jp/p/3021',
    completed_at: '2026-04-30T10:15:00+09:00',
    subs_order_id: null,
    shipping_address: {
      family_name: '吉田',
      given_name: '誠',
      zip: '810-0001',
      prefecture: '福岡県',
      city: '福岡市中央区',
      street: '天神1-7-11',
      building: 'イムズ 801号',
    },
    line_items: [
      { product_code: 'SU00', name: 'Lifewell スペシャルUV（単品）', quantity: 1, price: 3980 },
    ],
  },
  {
    id: 200022,
    number: 'EC-0200022',
    state: 'complete',
    payment_state: 'paid',
    shipment_state: 'ready',
    times: 3,
    is_first_order: false,
    payment_method_id: 1,
    payment_method_name: 'クレジットカード',
    o_plux_result: null,
    o_plux_description: null,
    purchase_url: 'https://lifewell.jp/p/3022',
    completed_at: '2026-04-30T11:40:00+09:00',
    subs_order_id: null,
    shipping_address: {
      family_name: '林',
      given_name: '由美',
      zip: '640-8032',
      prefecture: '和歌山県',
      city: '和歌山市友田町',
      street: '5-18',
      building: '',
    },
    line_items: [
      { product_code: 'EA00', name: 'Lifewell エイジングケア（単品）', quantity: 1, price: 5980 },
      { product_code: 'LW-1002', name: 'Lifewellビタミンサプリ 30粒', quantity: 1, price: 3800 },
    ],
  },
  {
    id: 200023,
    number: 'EC-0200023',
    state: 'complete',
    payment_state: 'paid',
    shipment_state: 'ready',
    times: 1,
    is_first_order: true,
    payment_method_id: 1,
    payment_method_name: 'クレジットカード',
    o_plux_result: 'OK',
    o_plux_description: null,
    purchase_url: 'https://lifewell.jp/p/3023',
    completed_at: '2026-04-30T13:00:00+09:00',
    subs_order_id: null,
    shipping_address: {
      family_name: '岡田',
      given_name: '剛',
      zip: '700-0901',
      prefecture: '岡山県',
      city: '岡山市北区',
      street: '本町3-1',
      building: 'OKAYAMAビル 605号',
    },
    line_items: [
      { product_code: 'WB00', name: 'Lifewell ウォーターバランス（単品）', quantity: 1, price: 4480 },
    ],
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// グループ5: 購入URL確認（5件） id: 200024-200028
// times===1 + purchase_url に 'test'/'defo' を含む
// ─────────────────────────────────────────────────────────────────────────────
const purchaseUrlOrders = [
  {
    id: 200024,
    number: 'EC-0200024',
    state: 'complete',
    payment_state: 'paid',
    shipment_state: 'ready',
    times: 1,
    is_first_order: true,
    payment_method_id: 1,
    payment_method_name: 'クレジットカード',
    o_plux_result: 'OK',
    o_plux_description: null,
    purchase_url: 'https://lifewell.jp/test/p/3024',
    completed_at: '2026-04-30T08:20:00+09:00',
    subs_order_id: null,
    shipping_address: {
      family_name: '清水',
      given_name: '拓朗',
      zip: '190-0012',
      prefecture: '東京都',
      city: '立川市',
      street: '曙町2-3-13',
      building: '',
    },
    line_items: [
      { product_code: 'LW-1001', name: 'Lifewellコラーゲン 60粒', quantity: 1, price: 5400 },
    ],
  },
  {
    id: 200025,
    number: 'EC-0200025',
    state: 'complete',
    payment_state: 'paid',
    shipment_state: 'ready',
    times: 1,
    is_first_order: true,
    payment_method_id: 1,
    payment_method_name: 'クレジットカード',
    o_plux_result: 'OK',
    o_plux_description: null,
    purchase_url: 'https://lifewell-defo.jp/p/3025',
    completed_at: '2026-04-30T09:50:00+09:00',
    subs_order_id: null,
    shipping_address: {
      family_name: '田村',
      given_name: '涼子',
      zip: '260-0045',
      prefecture: '千葉県',
      city: '千葉市中央区',
      street: '弁天2-1-1',
      building: '',
    },
    line_items: [
      { product_code: 'LW-1003', name: 'Lifewell乳酸菌プラス 90粒', quantity: 1, price: 6800 },
    ],
  },
  {
    id: 200026,
    number: 'EC-0200026',
    state: 'complete',
    payment_state: 'paid',
    shipment_state: 'ready',
    times: 1,
    is_first_order: true,
    payment_method_id: 1,
    payment_method_name: 'クレジットカード',
    o_plux_result: 'OK',
    o_plux_description: null,
    purchase_url: 'https://lifewell.jp/test-lp/p/3026',
    completed_at: '2026-04-30T10:30:00+09:00',
    subs_order_id: null,
    shipping_address: {
      family_name: '村田',
      given_name: '智恵',
      zip: '330-0801',
      prefecture: '埼玉県',
      city: 'さいたま市大宮区',
      street: '土手町1-1',
      building: '',
    },
    line_items: [
      { product_code: 'LW-1004', name: 'Lifewellマルチビタミン 60粒', quantity: 1, price: 4200 },
    ],
  },
  {
    id: 200027,
    number: 'EC-0200027',
    state: 'complete',
    payment_state: 'paid',
    shipment_state: 'ready',
    times: 1,
    is_first_order: true,
    payment_method_id: 1,
    payment_method_name: 'クレジットカード',
    o_plux_result: 'OK',
    o_plux_description: null,
    purchase_url: 'https://lifewell-test.jp/p/3027',
    completed_at: '2026-04-30T11:10:00+09:00',
    subs_order_id: null,
    shipping_address: {
      family_name: '川口',
      given_name: '祐介',
      zip: '420-0853',
      prefecture: '静岡県',
      city: '静岡市葵区',
      street: '追手町4-1',
      building: '',
    },
    line_items: [
      { product_code: 'LW-1002', name: 'Lifewellビタミンサプリ 30粒', quantity: 2, price: 3800 },
    ],
  },
  {
    id: 200028,
    number: 'EC-0200028',
    state: 'complete',
    payment_state: 'paid',
    shipment_state: 'ready',
    times: 1,
    is_first_order: true,
    payment_method_id: 1,
    payment_method_name: 'クレジットカード',
    o_plux_result: 'OK',
    o_plux_description: null,
    purchase_url: 'https://lifewell.jp/defo-campaign/3028',
    completed_at: '2026-04-30T12:45:00+09:00',
    subs_order_id: null,
    shipping_address: {
      family_name: '坂本',
      given_name: '亮太',
      zip: '380-0823',
      prefecture: '長野県',
      city: '長野市南千歳',
      street: '1-22-8',
      building: '長野センタービル 302号',
    },
    line_items: [
      { product_code: 'LW-1001', name: 'Lifewellコラーゲン 60粒', quantity: 1, price: 5400 },
    ],
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// グループ6: O-PLUX審査（7件） id: 200029-200035
// times===1 + o_plux_result==='REVIEW' + description あり
// ─────────────────────────────────────────────────────────────────────────────
const opluxOrders = [
  {
    id: 200029,
    number: 'EC-0200029',
    state: 'complete',
    payment_state: 'paid',
    shipment_state: 'ready',
    times: 1,
    is_first_order: true,
    payment_method_id: 1,
    payment_method_name: 'クレジットカード',
    o_plux_result: 'REVIEW',
    o_plux_description: 'ホテル住所への配送。住所確認推奨。',
    purchase_url: 'https://lifewell.jp/p/3029',
    completed_at: '2026-04-30T08:25:00+09:00',
    subs_order_id: null,
    shipping_address: {
      family_name: '宮本',
      given_name: '健',
      zip: '105-0003',
      prefecture: '東京都',
      city: '港区',
      street: '西新橋1-2-9',
      building: '日比谷セントラルビル 2401号',
    },
    line_items: [
      { product_code: 'LW-1001', name: 'Lifewellコラーゲン 60粒', quantity: 1, price: 5400 },
    ],
  },
  {
    id: 200030,
    number: 'EC-0200030',
    state: 'complete',
    payment_state: 'paid',
    shipment_state: 'ready',
    times: 1,
    is_first_order: true,
    payment_method_id: 1,
    payment_method_name: 'クレジットカード',
    o_plux_result: 'REVIEW',
    o_plux_description: '住所不備の可能性あり。番地情報が不明確。',
    purchase_url: 'https://lifewell.jp/p/3030',
    completed_at: '2026-04-30T09:05:00+09:00',
    subs_order_id: null,
    shipping_address: {
      family_name: '藤田',
      given_name: '理恵',
      zip: '060-0807',
      prefecture: '北海道',
      city: '札幌市北区',
      street: '北7条西2丁目',
      building: '',
    },
    line_items: [
      { product_code: 'LW-1004', name: 'Lifewellマルチビタミン 60粒', quantity: 1, price: 4200 },
    ],
  },
  {
    id: 200031,
    number: 'EC-0200031',
    state: 'complete',
    payment_state: 'paid',
    shipment_state: 'ready',
    times: 1,
    is_first_order: true,
    payment_method_id: 1,
    payment_method_name: 'クレジットカード',
    o_plux_result: 'REVIEW',
    o_plux_description: '不正利用の疑いあり。過去に同一決済手段でキャンセル歴。',
    purchase_url: 'https://lifewell.jp/p/3031',
    completed_at: '2026-04-30T09:55:00+09:00',
    subs_order_id: null,
    shipping_address: {
      family_name: '大野',
      given_name: '拓',
      zip: '460-0008',
      prefecture: '愛知県',
      city: '名古屋市中区',
      street: '栄4-1-1',
      building: '中日ビル 503号',
    },
    line_items: [
      { product_code: 'LW-1003', name: 'Lifewell乳酸菌プラス 90粒', quantity: 2, price: 6800 },
    ],
  },
  {
    id: 200032,
    number: 'EC-0200032',
    state: 'complete',
    payment_state: 'paid',
    shipment_state: 'ready',
    times: 1,
    is_first_order: true,
    payment_method_id: 1,
    payment_method_name: 'クレジットカード',
    o_plux_result: 'REVIEW',
    o_plux_description: 'ホテル・旅館への配送の可能性。住所要確認。',
    purchase_url: 'https://lifewell.jp/p/3032',
    completed_at: '2026-04-30T10:40:00+09:00',
    subs_order_id: null,
    shipping_address: {
      family_name: '中島',
      given_name: '薫',
      zip: '604-0924',
      prefecture: '京都府',
      city: '京都市中京区',
      street: '二条城町541',
      building: 'ホテルグランヴィア 1204号',
    },
    line_items: [
      { product_code: 'LW-1002', name: 'Lifewellビタミンサプリ 30粒', quantity: 1, price: 3800 },
    ],
  },
  {
    id: 200033,
    number: 'EC-0200033',
    state: 'complete',
    payment_state: 'paid',
    shipment_state: 'ready',
    times: 1,
    is_first_order: true,
    payment_method_id: 1,
    payment_method_name: 'クレジットカード',
    o_plux_result: 'REVIEW',
    o_plux_description: '複数デバイスからの注文検知。本人確認推奨。',
    purchase_url: 'https://lifewell.jp/p/3033',
    completed_at: '2026-04-30T11:50:00+09:00',
    subs_order_id: null,
    shipping_address: {
      family_name: '長谷川',
      given_name: '雪乃',
      zip: '231-0062',
      prefecture: '神奈川県',
      city: '横浜市中区',
      street: '桜木町1-1-7',
      building: 'コリドー街ビル 401号',
    },
    line_items: [
      { product_code: 'LW-1001', name: 'Lifewellコラーゲン 60粒', quantity: 1, price: 5400 },
    ],
  },
  {
    id: 200034,
    number: 'EC-0200034',
    state: 'complete',
    payment_state: 'paid',
    shipment_state: 'ready',
    times: 1,
    is_first_order: true,
    payment_method_id: 1,
    payment_method_name: 'クレジットカード',
    o_plux_result: 'REVIEW',
    o_plux_description: '転売リスクあり。過去に大量購入の記録。',
    purchase_url: 'https://lifewell.jp/p/3034',
    completed_at: '2026-04-30T12:20:00+09:00',
    subs_order_id: null,
    shipping_address: {
      family_name: '矢野',
      given_name: '誠一',
      zip: '700-0024',
      prefecture: '岡山県',
      city: '岡山市北区',
      street: '駅元町1-5',
      building: '',
    },
    line_items: [
      { product_code: 'LW-1003', name: 'Lifewell乳酸菌プラス 90粒', quantity: 3, price: 6800 },
    ],
  },
  {
    id: 200035,
    number: 'EC-0200035',
    state: 'complete',
    payment_state: 'paid',
    shipment_state: 'ready',
    times: 1,
    is_first_order: true,
    payment_method_id: 1,
    payment_method_name: 'クレジットカード',
    o_plux_result: 'REVIEW',
    o_plux_description: '住所が存在しない可能性あり。郵便番号と住所が不一致。',
    purchase_url: 'https://lifewell.jp/p/3035',
    completed_at: '2026-04-30T13:15:00+09:00',
    subs_order_id: null,
    shipping_address: {
      family_name: '安田',
      given_name: '和代',
      zip: '810-0042',
      prefecture: '福岡県',
      city: '福岡市中央区',
      street: '赤坂1-15-33',
      building: '',
    },
    line_items: [
      { product_code: 'LW-1004', name: 'Lifewellマルチビタミン 60粒', quantity: 1, price: 4200 },
    ],
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// グループ7: 重複注文（4件 = 2ペア） id: 200036-200039
// ─────────────────────────────────────────────────────────────────────────────
const duplicateOrders = [
  // ペア1: 同一氏名
  {
    id: 200036,
    number: 'EC-0200036',
    state: 'complete',
    payment_state: 'paid',
    shipment_state: 'ready',
    times: 1,
    is_first_order: true,
    payment_method_id: 1,
    payment_method_name: 'クレジットカード',
    o_plux_result: 'OK',
    o_plux_description: null,
    purchase_url: 'https://lifewell.jp/p/3036',
    completed_at: '2026-04-30T08:35:00+09:00',
    subs_order_id: null,
    shipping_address: {
      family_name: '田中',
      given_name: '美智子',
      zip: '135-0016',
      prefecture: '東京都',
      city: '江東区',
      street: '東陽4-11-28',
      building: '',
    },
    line_items: [
      { product_code: 'LW-1001', name: 'Lifewellコラーゲン 60粒', quantity: 1, price: 5400 },
    ],
  },
  {
    id: 200037,
    number: 'EC-0200037',
    state: 'complete',
    payment_state: 'paid',
    shipment_state: 'ready',
    times: 1,
    is_first_order: true,
    payment_method_id: 1,
    payment_method_name: 'クレジットカード',
    o_plux_result: 'OK',
    o_plux_description: null,
    purchase_url: 'https://lifewell.jp/p/3037',
    completed_at: '2026-04-30T08:50:00+09:00',
    subs_order_id: null,
    shipping_address: {
      family_name: '田中',
      given_name: '美智子',
      zip: '135-0016',
      prefecture: '東京都',
      city: '江東区',
      street: '東陽4-11-29',
      building: 'サニーハイツ 203号',
    },
    line_items: [
      { product_code: 'LW-1003', name: 'Lifewell乳酸菌プラス 90粒', quantity: 1, price: 6800 },
    ],
  },
  // ペア2: 同一住所
  {
    id: 200038,
    number: 'EC-0200038',
    state: 'complete',
    payment_state: 'paid',
    shipment_state: 'ready',
    times: 1,
    is_first_order: true,
    payment_method_id: 1,
    payment_method_name: 'クレジットカード',
    o_plux_result: 'OK',
    o_plux_description: null,
    purchase_url: 'https://lifewell.jp/p/3038',
    completed_at: '2026-04-30T09:15:00+09:00',
    subs_order_id: null,
    shipping_address: {
      family_name: '鈴木',
      given_name: '一太郎',
      zip: '545-0051',
      prefecture: '大阪府',
      city: '大阪市阿倍野区',
      street: '旭町1-2-2',
      building: '大阪医療センター隣 101号',
    },
    line_items: [
      { product_code: 'LW-1002', name: 'Lifewellビタミンサプリ 30粒', quantity: 1, price: 3800 },
    ],
  },
  {
    id: 200039,
    number: 'EC-0200039',
    state: 'complete',
    payment_state: 'paid',
    shipment_state: 'ready',
    times: 1,
    is_first_order: true,
    payment_method_id: 1,
    payment_method_name: 'クレジットカード',
    o_plux_result: 'OK',
    o_plux_description: null,
    purchase_url: 'https://lifewell.jp/p/3039',
    completed_at: '2026-04-30T09:30:00+09:00',
    subs_order_id: null,
    shipping_address: {
      family_name: '鈴木',
      given_name: '花子',
      zip: '545-0051',
      prefecture: '大阪府',
      city: '大阪市阿倍野区',
      street: '旭町1-2-2',
      building: '大阪医療センター隣 101号',
    },
    line_items: [
      { product_code: 'LW-1004', name: 'Lifewellマルチビタミン 60粒', quantity: 1, price: 4200 },
    ],
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// グループ8: 通常（出荷確認）（11件） id: 200040-200050
// 一部 is_first_order: true（住所校正タスクにも表示）
// ─────────────────────────────────────────────────────────────────────────────
const normalOrders = [
  {
    id: 200040,
    number: 'EC-0200040',
    state: 'complete',
    payment_state: 'paid',
    shipment_state: 'ready',
    times: 1,
    is_first_order: true,
    payment_method_id: 1,
    payment_method_name: 'クレジットカード',
    o_plux_result: 'OK',
    o_plux_description: null,
    purchase_url: 'https://lifewell.jp/p/3040',
    completed_at: '2026-04-30T07:30:00+09:00',
    subs_order_id: 50040,
    shipping_address: {
      family_name: '西村',
      given_name: '彩加',
      zip: '113-0033',
      prefecture: '東京都',
      city: '文京区',
      street: '本郷3-7-1',
      building: '',
    },
    line_items: [
      { product_code: 'LW-1001', name: 'Lifewellコラーゲン 60粒', quantity: 1, price: 5400 },
    ],
  },
  {
    id: 200041,
    number: 'EC-0200041',
    state: 'complete',
    payment_state: 'paid',
    shipment_state: 'ready',
    times: 5,
    is_first_order: false,
    payment_method_id: 1,
    payment_method_name: 'クレジットカード',
    o_plux_result: null,
    o_plux_description: null,
    purchase_url: 'https://lifewell.jp/p/3041',
    completed_at: '2026-04-30T07:45:00+09:00',
    subs_order_id: 50041,
    shipping_address: {
      family_name: '森田',
      given_name: '陽子',
      zip: '980-0021',
      prefecture: '宮城県',
      city: '仙台市青葉区',
      street: '中央2-11-1',
      building: '仙台マークワン 1805号',
    },
    line_items: [
      { product_code: 'LW-1003', name: 'Lifewell乳酸菌プラス 90粒', quantity: 1, price: 6800 },
    ],
  },
  {
    id: 200042,
    number: 'EC-0200042',
    state: 'complete',
    payment_state: 'paid',
    shipment_state: 'ready',
    times: 3,
    is_first_order: false,
    payment_method_id: 1,
    payment_method_name: 'クレジットカード',
    o_plux_result: null,
    o_plux_description: null,
    purchase_url: 'https://lifewell.jp/p/3042',
    completed_at: '2026-04-30T08:00:00+09:00',
    subs_order_id: 50042,
    shipping_address: {
      family_name: '浜田',
      given_name: '光子',
      zip: '657-0854',
      prefecture: '兵庫県',
      city: '神戸市灘区',
      street: '摩耶埠頭3-1',
      building: '',
    },
    line_items: [
      { product_code: 'LW-1002', name: 'Lifewellビタミンサプリ 30粒', quantity: 2, price: 3800 },
    ],
  },
  {
    id: 200043,
    number: 'EC-0200043',
    state: 'complete',
    payment_state: 'paid',
    shipment_state: 'ready',
    times: 1,
    is_first_order: true,
    payment_method_id: 1,
    payment_method_name: 'クレジットカード',
    o_plux_result: 'OK',
    o_plux_description: null,
    purchase_url: 'https://lifewell.jp/p/3043',
    completed_at: '2026-04-30T08:15:00+09:00',
    subs_order_id: 50043,
    shipping_address: {
      family_name: '藤原',
      given_name: '幸太郎',
      zip: '500-0001',
      prefecture: '岐阜県',
      city: '岐阜市神田町',
      street: '8-4',
      building: '岐阜シティタワー43 3504号',
    },
    line_items: [
      { product_code: 'LW-1004', name: 'Lifewellマルチビタミン 60粒', quantity: 1, price: 4200 },
    ],
  },
  {
    id: 200044,
    number: 'EC-0200044',
    state: 'complete',
    payment_state: 'paid',
    shipment_state: 'ready',
    times: 7,
    is_first_order: false,
    payment_method_id: 1,
    payment_method_name: 'クレジットカード',
    o_plux_result: null,
    o_plux_description: null,
    purchase_url: 'https://lifewell.jp/p/3044',
    completed_at: '2026-04-30T08:30:00+09:00',
    subs_order_id: 50044,
    shipping_address: {
      family_name: '山口',
      given_name: '典江',
      zip: '320-0026',
      prefecture: '栃木県',
      city: '宇都宮市馬場通り',
      street: '3-1-1',
      building: 'フュージョン宇都宮 1002号',
    },
    line_items: [
      { product_code: 'LW-1001', name: 'Lifewellコラーゲン 60粒', quantity: 1, price: 5400 },
    ],
  },
  {
    id: 200045,
    number: 'EC-0200045',
    state: 'complete',
    payment_state: 'paid',
    shipment_state: 'ready',
    times: 2,
    is_first_order: false,
    payment_method_id: 1,
    payment_method_name: 'クレジットカード',
    o_plux_result: null,
    o_plux_description: null,
    purchase_url: 'https://lifewell.jp/p/3045',
    completed_at: '2026-04-30T09:00:00+09:00',
    subs_order_id: 50045,
    shipping_address: {
      family_name: '松本',
      given_name: '里佳',
      zip: '380-0838',
      prefecture: '長野県',
      city: '長野市大字長野',
      street: '大字長野元善町491-5',
      building: '',
    },
    line_items: [
      { product_code: 'LW-1003', name: 'Lifewell乳酸菌プラス 90粒', quantity: 1, price: 6800 },
    ],
  },
  {
    id: 200046,
    number: 'EC-0200046',
    state: 'complete',
    payment_state: 'paid',
    shipment_state: 'ready',
    times: 4,
    is_first_order: false,
    payment_method_id: 1,
    payment_method_name: 'クレジットカード',
    o_plux_result: null,
    o_plux_description: null,
    purchase_url: 'https://lifewell.jp/p/3046',
    completed_at: '2026-04-30T09:30:00+09:00',
    subs_order_id: 50046,
    shipping_address: {
      family_name: '池田',
      given_name: '哲郎',
      zip: '760-0020',
      prefecture: '香川県',
      city: '高松市錦町',
      street: '1-10-3',
      building: '',
    },
    line_items: [
      { product_code: 'LW-1002', name: 'Lifewellビタミンサプリ 30粒', quantity: 2, price: 3800 },
    ],
  },
  {
    id: 200047,
    number: 'EC-0200047',
    state: 'complete',
    payment_state: 'paid',
    shipment_state: 'ready',
    times: 1,
    is_first_order: true,
    payment_method_id: 1,
    payment_method_name: 'クレジットカード',
    o_plux_result: 'OK',
    o_plux_description: null,
    purchase_url: 'https://lifewell.jp/p/3047',
    completed_at: '2026-04-30T10:00:00+09:00',
    subs_order_id: 50047,
    shipping_address: {
      family_name: '野口',
      given_name: '千尋',
      zip: '790-0001',
      prefecture: '愛媛県',
      city: '松山市一番町',
      street: '4-4-2',
      building: 'ホテル松山 303号',
    },
    line_items: [
      { product_code: 'LW-1004', name: 'Lifewellマルチビタミン 60粒', quantity: 1, price: 4200 },
    ],
  },
  {
    id: 200048,
    number: 'EC-0200048',
    state: 'complete',
    payment_state: 'paid',
    shipment_state: 'ready',
    times: 6,
    is_first_order: false,
    payment_method_id: 1,
    payment_method_name: 'クレジットカード',
    o_plux_result: null,
    o_plux_description: null,
    purchase_url: 'https://lifewell.jp/p/3048',
    completed_at: '2026-04-30T10:30:00+09:00',
    subs_order_id: 50048,
    shipping_address: {
      family_name: '片山',
      given_name: '敦子',
      zip: '880-0805',
      prefecture: '宮崎県',
      city: '宮崎市橘通東',
      street: '3-1-1',
      building: '',
    },
    line_items: [
      { product_code: 'LW-1001', name: 'Lifewellコラーゲン 60粒', quantity: 1, price: 5400 },
    ],
  },
  {
    id: 200049,
    number: 'EC-0200049',
    state: 'complete',
    payment_state: 'paid',
    shipment_state: 'ready',
    times: 2,
    is_first_order: false,
    payment_method_id: 1,
    payment_method_name: 'クレジットカード',
    o_plux_result: null,
    o_plux_description: null,
    purchase_url: 'https://lifewell.jp/p/3049',
    completed_at: '2026-04-30T11:00:00+09:00',
    subs_order_id: 50049,
    shipping_address: {
      family_name: '三浦',
      given_name: '正則',
      zip: '400-0031',
      prefecture: '山梨県',
      city: '甲府市丸の内',
      street: '1-6-1',
      building: 'NHK甲府放送局ビル 205号',
    },
    line_items: [
      { product_code: 'LW-1003', name: 'Lifewell乳酸菌プラス 90粒', quantity: 1, price: 6800 },
    ],
  },
  {
    id: 200050,
    number: 'EC-0200050',
    state: 'complete',
    payment_state: 'paid',
    shipment_state: 'ready',
    times: 3,
    is_first_order: false,
    payment_method_id: 1,
    payment_method_name: 'クレジットカード',
    o_plux_result: null,
    o_plux_description: null,
    purchase_url: 'https://lifewell.jp/p/3050',
    completed_at: '2026-04-30T11:30:00+09:00',
    subs_order_id: 50050,
    shipping_address: {
      family_name: '石田',
      given_name: '京子',
      zip: '630-8301',
      prefecture: '奈良県',
      city: '奈良市高畑町',
      street: '1096',
      building: '',
    },
    line_items: [
      { product_code: 'LW-1002', name: 'Lifewellビタミンサプリ 30粒', quantity: 2, price: 3800 },
    ],
  },
];

/**
 * イベントデモ用ダミー受注50件を返す
 * @returns {Array} 50件の受注オブジェクト配列
 */
export function getDemoOrders() {
  return [
    ...paymentErrorOrders,    // 200001-200006 (6件)
    ...nameAnomalyOrders,     // 200007-200013 (7件)
    ...npPaymentOrders,       // 200014-200018 (5件)
    ...singleItemOrders,      // 200019-200023 (5件)
    ...purchaseUrlOrders,     // 200024-200028 (5件)
    ...opluxOrders,           // 200029-200035 (7件)
    ...duplicateOrders,       // 200036-200039 (4件)
    ...normalOrders,          // 200040-200050 (11件)
  ];
}
